CREATE DATABASE IF NOT EXISTS mywebapp
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE mywebapp;

CREATE TABLE IF NOT EXISTS items (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    quantity   INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
